### ISSUE TITLE
player.asset_digest is null

### ISSUE THREAD

**Issue by RoccoDeveloping** [maierfelix/POGOserver#115]
The new issue is:

`Gotrequest: GET_ASSET_DIGEST 

Got request: CHECK_CHALLENGE 

Got request: GET_HATCHED_EGGS 

Got request: GET_INVENTORY 

Got request: CHECK_AWARDED_BADGES 

Got request: DOWNLOAD_SETTINGS 

[Console] Response error: TypeError: Cannot read property 'buffer' of null`

I downloaded version 0.4.9. When I do ./run-linux.sh I get this error:
`Error: Cannot find module 'pokemongo-protobuf'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/rocco/Scaricati/POGOserver-0.4.9/src/setup.js:5:1)
    at Module._compile (module.js:541:32)
    at loader (/home/rocco/Scaricati/POGOserver-0.4.9/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/rocco/Scaricati/POGOserver-0.4.9/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/rocco/Scaricati/POGOserver-0.4.9/src/index.js:16:1)
    at Module._compile (module.js:541:32)
    at loader (/home/rocco/Scaricati/POGOserver-0.4.9/node_modules/babel-register/lib/node.js:146:5)
`
I cannot do anything. What should I do now?

I'm using Arch Linux 2016.08.01 (Linux 4.7.2) x64

**Comment by DracoMilesX** [comment]
Can you try the latest version? So just glit clone the master branch? It should be solved in that one.

**Comment by RoccoDeveloping** [comment]
It wasn't the version. I solved it. G++ (so GCC) was missing. I installed it and voilà. However, the new commits are broken.

**Comment by RoccoDeveloping** [comment]
Can you help me to another issue please? I'd like to know how you can pop up that "New Pokestop" Web GUI. If I try to connect to localhost:3000 it says "Unknown protocol etc."

**Comment by DracoMilesX** [comment]
You need the api branch for that.

**Comment by RoccoDeveloping** [comment]
How can I do that? I know how to clone the branch. Then what should I do?

**Comment by DracoMilesX** [comment]
Install apache2 or nginx whichever you prefer and move the files to the root of the webserver then just connect to localhost/<foldername>.

**Comment by RoccoDeveloping** [comment]
I cannot find /var/www. Any other directories?

**Comment by DracoMilesX** [comment]
Try /srv/http for Arch Linux https://wiki.archlinux.org/index.php/Apache_HTTP_Server

**Comment by RoccoDeveloping** [comment]
Oh nvm it was /opt/lampp/htdocs Thanks a lot! Stay tuned so I poke you if I have any other issues.

**Comment by RoccoDeveloping** [comment]
I have another issue.
`Got request: GET_ASSET_DIGEST
Got request: CHECK_CHALLENGE
Got request: GET_HATCHED_EGGS
Got request: GET_INVENTORY
Got request: CHECK_AWARDED_BADGES
Got request: DOWNLOAD_SETTINGS
[Console] Response error: TypeError: Cannot read property 'buffer' of null
`

**Comment by RoccoDeveloping** [comment]
When I try to connect the Loading bar gets to half and hangs there.

**Comment by RoccoDeveloping** [comment]
Please help!
