### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by thelemonenergy** [maierfelix/POGOserver#16]
This happens whenever I try to login

#####
Got request: GET_PLAYER
Unhandled exception occurred:  undefined
TypeError: Cannot read property 'replace' of null
    at GameServer.onRequest (request.js:87:21)
    at GameServer.routeRequest (request.js:173:12)
    at IncomingMessage.<anonymous> (index.js:131:14)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
[Console] The server has crashed!

**Comment by shinsen26** [comment]
InGame, log into google account, this will fix your issue
