### ISSUE TITLE
Cannot find module 'pngjs'

### ISSUE THREAD

**Issue by MemoryPattern** [maierfelix/POGOserver#176]
Error: Cannot find module 'pngjs'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/POGO/POGOserver/src/index.js:19:1)
    at Module._compile (module.js:541:32)
    at loader (/POGO/POGOserver/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/POGO/POGOserver                                                                             /node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

**Comment by DracoMilesX** [comment]
`"pngjs": "^3.0.0",`

Add that to package.json it got removed but the check for it/requirements are still their.

**Comment by Cronick** [comment]
Remove line 19 in /src/index.js
