### ISSUE TITLE
TypeError on Login

### ISSUE THREAD

**Issue by gcsoftware** [maierfelix/POGOserver#188]
Everytime I attempt to login with a Google account the server seems to throw this error. I'm currently using v0.5.9, but this has also occured on other versions. I've tried different accounts and have followed just about every direction to a tee.

OS: Ubuntu 16.04 LTS on VirtualBox | Network: Bridged (Same Subnet, LAN)
Device: N920i (Note 5) running Android Marshmallow (6.0.1).
Using a modified 0.35.0 apk with cert pinning disabled and Pokemon Xposed Module to direct to endpoint.

[Console] Unhandled exception occurred: 
[Console] TypeError: Cannot read property 'contents' of undefined
[Console] TypeError: Cannot read property 'contents' of undefined
    at GameServer.authenticatePlayer (/home/dev/POGOserver/src/request.js:190:31)
    at GameServer.onRequest (/home/dev/POGOserver/src/request.js:97:10)
    at GameServer.processRpcRequest (/home/dev/POGOserver/src/request.js:84:10)
    at GameServer.routeRequest (/home/dev/POGOserver/src/request.js:28:12)
    at IncomingMessage.<anonymous> (/home/dev/POGOserver/src/http.js:22:12)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
[Console] The server has crashed!

**Comment by gcsoftware** [comment]
Figured out the solution. Don't use any modified apk with cert pinning disabled. After installing a stock 0.35.0 apk and letting the Xposed Module handle the rest it works perfectly.
