### ISSUE TITLE
Error - Couldn't find preset " + (0, _stringify2.default)(val) +

### ISSUE THREAD

**Issue by nisanb** [maierfelix/POGOserver#20]
I'm trying to run on win 10 64-bit

https://s3.postimg.org/5d6ei5hhf/pogoserver.png

**Comment by TachyonRSA** [comment]
`npm install babel-preset-stage-0`

Should fix it for you.

**Comment by nisanb** [comment]
Hi !
Thanks for tryign to help me.
I tried, but still same error.

[
> POGOServer@0.2.5 start C:\pogoserver
> nodemon --exec npm run babel-node -- ./src/index.js

[nodemon] 1.10.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `npm run babel-node ./src/index.js`

> POGOServer@0.2.5 babel-node C:\pogoserver
> babel-node --presets=es2015 "./src/index.js"

C:\Users\nisan\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:321
          throw new Error("Couldn't find preset " + (0, _stringify2.default)(val) + " relative to directory " + (0, _stringify2.default)(dirname));
          ^

Error: Couldn't find preset "stage-0" relative to directory "C:\\pogoserver"
    at C:\Users\nisan\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:321:17
    at Array.map (native)
    at OptionManager.resolvePresets (C:\Users\nisan\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:305:20)
    at OptionManager.mergePresets (C:\Users\nisan\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:288:10)
    at OptionManager.mergeOptions (C:\Users\nisan\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:14)
    at OptionManager.init (C:\Users\nisan\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:383:12)
    at compile (C:\Users\nisan\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-register\lib\node.js:103:45)
    at loader (C:\Users\nisan\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-register\lib\node.js:148:14)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\nisan\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-register\lib\node.js:158:7)
    at Module.load (module.js:473:32)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "babel-node" "./src/index.js"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! POGOServer@0.2.5 babel-node: `babel-node --presets=es2015 "./src/index.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the POGOServer@0.2.5 babel-node script 'babel-node --presets=es2015 "./src/index.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the POGOServer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node --presets=es2015 "./src/index.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs POGOServer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls POGOServer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\pogoserver\npm-debug.log
[nodemon] app crashed - waiting for file changes before starting...
](url)

**Comment by nisanb** [comment]
OK!
Server is running, but:

> POGOServer@0.2.5 babel-node C:\pogoserver
> babel-node --presets=es2015 "./src/index.js"

            ______ _____ _____ _____
            | ___ \  _  |  __ \  _  |
            | |_/ / | | | |  \/ | | | ___  ___ _ ____   _____ _ __
            |  __/| | | | | __| | | |/ __|/ _ \ '__\ \ / / _ \ '__|
            | |   \ \_/ / |_\ \ \_/ /\__ \  __/ |   \ V /  __/ |
            \_|    \___/ \____/\___/ |___/\___|_|    \_/ \___|_|

[Console] Booting server..
[Console] Created asset download session
[Console] MySQL connection established
[Console] Server running at 127.0.0.1:1232
[Console] Port 1232 is already in use!
[Console] The server has crashed!


I've tried changing ports a few times

Also, do I need to create a user in the DB?

**Comment by nisanb** [comment]
Working thanks
