### ISSUE TITLE
Error installing protobuf

### ISSUE THREAD

**Issue by GabrielTK** [maierfelix/POGOserver#208]
Hi, 
Sorry for writing too quickly, but I need to hurry.
I'm getting this little problem when running Install-Windows.bat:

```
C:\NodeJS\Projects\POGOServer\Core>set LIBPROTOBUF=%CD%\protobuf\lib

C:\NodeJS\Projects\POGOServer\Core>npm install node-protobuf

> node-protobuf@1.3.3 install C:\NodeJS\Projects\POGOServer\Core\node_modules\node-protobuf
> node-gyp rebuild


C:\NodeJS\Projects\POGOServer\Core\node_modules\node-protobuf>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Compilando os projetos desta solução um de cada vez. Para habilitar a compilação paralela, adicione a opção "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.targets(44,5): error MSB8020: The buil ds tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, either click the  Project menu or right-click the solution, and then select "Update VC++ Projects...". Install v140 to build using th e v140 build tools. [C:\NodeJS\Projects\POGOServer\Core\node_modules\node-protobuf\build\protobuf.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\NodeJS\Projects\POGOServer\Core\node_modules\node-protobuf
gyp ERR! node -v v5.7.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN POGOServer@0.5.9 license should be a valid SPDX license expression
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-protobuf"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! node-protobuf@1.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-protobuf@1.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-protobuf
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\NodeJS\Projects\POGOServer\Core\npm-debug.log
```

(NOTICE: I removed the && npm install, becaude I've already ran it.)
Thank you,
Gabriel

**Comment by GabrielTK** [comment]
Note 2: I've put all the files that were in the install folder inside a folder called protobuf at the POGOServer dir. (.../Projects/POGOServer/core/*protobuf*)

**Comment by GabrielTK** [comment]
Solved by running '%comspec% /k ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"" amd64' in cmd.
