### ISSUE TITLE
POGOserver doesn't show up

### ISSUE THREAD

**Issue by TheLuaDawge** [maierfelix/POGOserver#220]
I downloaded this from SkinFreak and this shows up:

C:\Users\Olivier\Desktop\POGOserver-master\node_modules\bindings\bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\Olivier\Desktop\POGOserver-master\node_modules\node-protobuf\build\protobuf.node
 → C:\Users\Olivier\Desktop\POGOserver-master\node_modules\node-protobuf\build\Debug\protobuf.node
 → C:\Users\Olivier\Desktop\POGOserver-master\node_modules\node-protobuf\build\Release\protobuf.node
 → C:\Users\Olivier\Desktop\POGOserver-master\node_modules\node-protobuf\out\Debug\protobuf.node
 → C:\Users\Olivier\Desktop\POGOserver-master\node_modules\node-protobuf\Debug\protobuf.node
 → C:\Users\Olivier\Desktop\POGOserver-master\node_modules\node-protobuf\out\Release\protobuf.node
 → C:\Users\Olivier\Desktop\POGOserver-master\node_modules\node-protobuf\Release\protobuf.node
 → C:\Users\Olivier\Desktop\POGOserver-master\node_modules\node-protobuf\build\default\protobuf.node
 → C:\Users\Olivier\Desktop\POGOserver-master\node_modules\node-protobuf\compiled\6.6.0\win32\x64\protobuf.node
    at bindings (C:\Users\Olivier\Desktop\POGOserver-master\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (C:\Users\Olivier\Desktop\POGOserver-master\node_modules\node-protobuf\protobuf.js:9:35)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Olivier\Desktop\POGOserver-master\node_modules\babel-register\lib\node.js:156:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Olivier\Desktop\POGOserver-master\node_modules\pokemongo-protobuf\index.js:2:16)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Olivier\Desktop\POGOserver-master\node_modules\babel-register\lib\node.js:156:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "babel-node" "./src/index.js"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! POGOServer@0.4.9 babel-node: `babel-node --presets=es2015 "./src/index.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the POGOServer@0.4.9 babel-node script 'babel-node --presets=es2015 "./src/index.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the POGOServer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node --presets=es2015 "./src/index.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs POGOServer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls POGOServer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Olivier\Desktop\POGOserver-master\npm-debug.log
[nodemon] app crashed - waiting for file changes before starting...

**Comment by DracoMilesX** [comment]
Download the latest master branch, install protobuf correctly.
