### ISSUE TITLE
Please Help! Errors!

### ISSUE THREAD

**Issue by EricPaulZ467** [maierfelix/POGOserver#243]
Hi! I've just founded your hack yesterday (I think this is the official website) in this guy channel, SkinFreak ("https://www.youtube.com/watch?v=jdKoPW_9HDY"). So I've been following the steps that he done, but at last it came out too many errors! Can someone help me fix?

This error appeared in Command Prompt.
> D:\POGOServer\POGOserver-master>npm install   && npm run start
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.14
> POGOServer@0.4.9 start D:\POGOServer\POGOserver-master
> nodemon --ignore tmp/ --ignore data/ --ignore logs/ --exec npm run babel-node
-- ./src/index.js
[nodemon] 1.10.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `npm run babel-node ./src/index.js`
> POGOServer@0.4.9 babel-node D:\POGOServer\POGOserver-master
> babel-node --presets=es2015 "./src/index.js"
D:\POGOServer\POGOserver-master\node_modules\bindings\bindings.js
:83
        throw e
        ^
Error: %1 is not a valid Win32 application.
\\?\D:\POGOServer\POGOserver-master\node_modules\node-protobuf\bu
ild\Release\protobuf.node
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (D:\POGOServer\POGOserver-master\node_modules\bin
dings\bindings.js:76:44)
    at Object.<anonymous> (D:\POGOServer\POGOserver-master\node_m
odules\node-protobuf\protobuf.js:9:35)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\Mewtwo hack n
o delete pls\POGOserver-master\node_modules\babel-register\lib\node.js:156:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\AdminPC\\A
ppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "babel-node" "./
src/index.js"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! POGOServer@0.4.9 babel-node: `babel-node --presets=es2015 "./src/index.
js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the POGOServer@0.4.9 babel-node script 'babel-node --presets=
es2015 "./src/index.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the POGOServer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node --presets=es2015 "./src/index.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs POGOServer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls POGOServer
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     D:\POGOServer\POGOserver-master\npm-debug.log
[nodemon] app crashed - waiting for file changes before starting...

And this error is in the 'log' file.
> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\AdminPC\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'babel-node',
1 verbose cli   './src/index.js' ]
2 info using npm@3.10.7
3 info using node@v6.7.0
4 verbose run-script [ 'prebabel-node', 'babel-node', 'postbabel-node' ]
5 info lifecycle POGOServer@0.4.9~prebabel-node: POGOServer@0.4.9
6 silly lifecycle POGOServer@0.4.9~prebabel-node: no script for prebabel-node, continuing
7 info lifecycle POGOServer@0.4.9~babel-node: POGOServer@0.4.9
8 verbose lifecycle POGOServer@0.4.9~babel-node: unsafe-perm in lifecycle true
9 verbose lifecycle POGOServer@0.4.9~babel-node: PATH: C:\Users\AdminPC\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\POGOServer\POGOserver-master\node_modules\.bin;C:\Users\AdminPC\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\POGOServer\POGOserver-master\node_modules\.bin;D:\Javla Mate V6 SnakeZ\Mewtwo-ing\Installation\Python\;D:\Javla Mate V6 SnakeZ\Mewtwo-ing\Installation\Python\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\PROGRA~1\MATROX~1\System32;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Windows Live\Shared;C:\Program Files\Cepstral\bin;D:\POGOServer\Important\Git\cmd;C:\Program Files\nodejs\;C:\Users\AdminPC\.dnx\bin;C:\Program Files\CMake\bin;C:\Users\AdminPC\AppData\Roaming\npm
10 verbose lifecycle POGOServer@0.4.9~babel-node: CWD: D:\POGOServer\POGOserver-master
11 silly lifecycle POGOServer@0.4.9~babel-node: Args: [ '/d /s /c', 'babel-node --presets=es2015 "./src/index.js"' ]
12 silly lifecycle POGOServer@0.4.9~babel-node: Returned: code: 1  signal: null
13 info lifecycle POGOServer@0.4.9~babel-node: Failed to exec babel-node script
14 verbose stack Error: POGOServer@0.4.9 babel-node: `babel-node --presets=es2015 "./src/index.js"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\AdminPC\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\AdminPC\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid POGOServer@0.4.9
16 verbose cwd D:\POGOServer\POGOserver-master
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\AdminPC\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "babel-node" "./src/index.js"
19 error node v6.7.0
20 error npm  v3.10.7
21 error code ELIFECYCLE
22 error POGOServer@0.4.9 babel-node: `babel-node --presets=es2015 "./src/index.js"`
22 error Exit status 1
23 error Failed at the POGOServer@0.4.9 babel-node script 'babel-node --presets=es2015 "./src/index.js"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the POGOServer package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     babel-node --presets=es2015 "./src/index.js"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs POGOServer
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls POGOServer
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by EricPaulZ467** [comment]
This my NPM and Xampp version:
Xampp : 7.0.8-0
NPM : 3.10.7

**Comment by DracoMilesX** [comment]
What happens if you use the master branch instead of v0.4.9?

**Comment by EricPaulZ467** [comment]
Maybe you guys can send me the complete zip of this program?

**Comment by GabrielTK** [comment]
@EricPaulZ467 [Here](https://github.com/maierfelix/POGOserver/archive/master.zip) it is. 
**BONUS:** Thanks to GitHub, this link will be **always** updated.

**Comment by EricPaulZ467** [comment]
Then, what do I do with this zip file?

**Comment by knownprankster** [comment]
can someone tell me how to fix these errors
error: code elifecycle
error: errno 1
Error: POGOServer@0.4.9 babel-node: `babel-node --presets=es2015 "./src/index.js"
error: exit status 1
error: failed at the pogoserver @0.4.9 bable-node script.
