### ISSUE TITLE
error Windows_NT 6.1.760 ( Help Me Please)

### ISSUE THREAD

**Issue by rodrigo22021998** [maierfelix/POGOserver#251]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\npm\\node.exe',
1 verbose cli   'C:\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle POGOServer@0.4.9~prestart: POGOServer@0.4.9
6 silly lifecycle POGOServer@0.4.9~prestart: no script for prestart, continuing
7 info lifecycle POGOServer@0.4.9~start: POGOServer@0.4.9
8 verbose lifecycle POGOServer@0.4.9~start: unsafe-perm in lifecycle true
9 verbose lifecycle POGOServer@0.4.9~start: PATH: C:\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\rodrigo\Downloads\Pre Setup Server Pokemon Go Server 4.9\Pokemon Go Server\POGOserver-master\POGOserver-master\node_modules\.bin;C:\npm;C:\npm; C:\Git\cmd;C:\npm\;C:\Users\rodrigo\AppData\Roaming\npm
10 verbose lifecycle POGOServer@0.4.9~start: CWD: C:\Users\rodrigo\Downloads\Pre Setup Server Pokemon Go Server 4.9\Pokemon Go Server\POGOserver-master\POGOserver-master
11 silly lifecycle POGOServer@0.4.9~start: Args: [ '/d /s /c',
11 silly lifecycle   'nodemon --ignore tmp/ --ignore data/ --ignore logs/ --exec npm run babel-node -- ./src/index.js' ]
12 silly lifecycle POGOServer@0.4.9~start: Returned: code: 1  signal: null
13 info lifecycle POGOServer@0.4.9~start: Failed to exec start script
14 verbose stack Error: POGOServer@0.4.9 start: `nodemon --ignore tmp/ --ignore data/ --ignore logs/ --exec npm run babel-node -- ./src/index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\npm\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid POGOServer@0.4.9
16 verbose cwd C:\Users\rodrigo\Downloads\Pre Setup Server Pokemon Go Server 4.9\Pokemon Go Server\POGOserver-master\POGOserver-master
17 error Windows_NT 6.1.7601
18 error argv "C:\\npm\\node.exe" "C:\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
19 error node v6.7.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error POGOServer@0.4.9 start: `nodemon --ignore tmp/ --ignore data/ --ignore logs/ --exec npm run babel-node -- ./src/index.js`
22 error Exit status 1
23 error Failed at the POGOServer@0.4.9 start script 'nodemon --ignore tmp/ --ignore data/ --ignore logs/ --exec npm run babel-node -- ./src/index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the POGOServer package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     nodemon --ignore tmp/ --ignore data/ --ignore logs/ --exec npm run babel-node -- ./src/index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs POGOServer
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls POGOServer
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by scorp12** [comment]
that same issue is listed many times in the closed issues list.

**Comment by scorp12** [comment]
basically easiest way is to run a linux system either on a computer or a vmware setup

**Comment by nliakm** [comment]
+ use the latest server version (0.6.0)

**Comment by rodrigo22021998** [comment]
how to install server version 0.6.0?? ( the github(pogoserver) not changed much..)

**Comment by rodrigo22021998** [comment]
and how to use the vmware , linux , windows 10? My is the 7
