### ISSUE TITLE
Error: Cannot find module 'pokemongo-protobuf'

### ISSUE THREAD

**Issue by LUCKASSs** [maierfelix/POGOserver#273]
Hello guys,
I got an error when I launch by `sudo npm run boot`

`luca@luca-desktop:~/POGOserver$ sudo npm run boot

> POGOServer@0.6.0 boot /home/luca/POGOserver
> npm run babel-node -- ./src/index.js

> POGOServer@0.6.0 babel-node /home/luca/POGOserver
> babel-node --presets=es2015 "./src/index.js"

module.js:328
    throw err;
    ^

Error: Cannot find module 'pokemongo-protobuf'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/luca/POGOserver/src/index.js:5:1)
    at Module._compile (module.js:410:26)
    at loader (/home/luca/POGOserver/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/luca/POGOserver/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "babel-node" "--" "./src/index.js"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! POGOServer@0.6.0 babel-node: `babel-node --presets=es2015 "./src/index.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the POGOServer@0.6.0 babel-node script 'babel-node --presets=es2015 "./src/index.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the POGOServer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node --presets=es2015 "./src/index.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs POGOServer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls POGOServer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/luca/POGOserver/npm-debug.log

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "boot"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! POGOServer@0.6.0 boot: `npm run babel-node -- ./src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the POGOServer@0.6.0 boot script 'npm run babel-node -- ./src/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the POGOServer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run babel-node -- ./src/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs POGOServer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls POGOServer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/luca/POGOserver/npm-debug.log
`

Thx

**Comment by Cronick** [comment]
Have you tried to run "npm install"?

**Comment by LUCKASSs** [comment]
I completly re-install the server, and that works fine !

**Comment by Cronick** [comment]
What provider do you use to login with?

**Comment by LUCKASSs** [comment]
Provider ?

**Comment by Cronick** [comment]
PTC/Google

**Comment by Cronick** [comment]
Only Google login is supported at the moment.

**Comment by LUCKASSs** [comment]
Ok thx

**Comment by Cronick** [comment]
Try to give me a screenshot of the web-browser console

**Comment by LUCKASSs** [comment]
Nothing happend : 

```
> POGOServer@0.6.0 api /home/luca/POGOserver
> npm run babel-node -- ./api/index.js


> POGOServer@0.6.0 babel-node /home/luca/POGOserver
> babel-node --presets=es2015 "./api/index.js"

Web-API for POGOserver running at => http://localhost:9000/
CTRL + C to shutdown
```

**Comment by Cronick** [comment]
Have you changed the cfg.js in the api folder to your server ip?

**Comment by LUCKASSs** [comment]
I just renamed the cfg to cfg.js
The ip is localhost (127.0.0.1) I have to change this ?

**Comment by Cronick** [comment]
If your server and API is hosted on the same machine, then you should not change it.

**Comment by LUCKASSs** [comment]
Now it said "connection failed".... I'm retarded or something ??

**Comment by LUCKASSs** [comment]
@Cronick

**Comment by LUCKASSs** [comment]
Any help pls for the "login failed" on the Web Ui ?
