### ISSUE TITLE
Failed to run "run-windows"

### ISSUE THREAD

**Issue by WonThesSik** [maierfelix/POGOserver#280]
Windows 10. After doing install-windows.bat and then run-windows.bat, this error message is created.

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'boot' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose run-script [ 'preboot', 'boot', 'postboot' ]
5 info preboot POGOServer@0.6.0
6 info boot POGOServer@0.6.0
7 verbose unsafe-perm in lifecycle true
8 info POGOServer@0.6.0 Failed to exec boot script
9 verbose stack Error: POGOServer@0.6.0 boot: `npm run babel-node -- ./src/index.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid POGOServer@0.6.0
11 verbose cwd C:\Users\David\Desktop\PGM-3.2.0\server
12 error Windows_NT 10.0.14393
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "boot"
14 error node v4.6.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error POGOServer@0.6.0 boot: `npm run babel-node -- ./src/index.js`
17 error Exit status 1
18 error Failed at the POGOServer@0.6.0 boot script 'npm run babel-node -- ./src/index.js'.
18 error This is most likely a problem with the POGOServer package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run babel-node -- ./src/index.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs POGOServer
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls POGOServer
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by Rendaman13** [comment]
Did you recieve an error message when running instal-windows.bat? If so, check to make sure you have protobuf installed correctly. If not, you might be forgetting cfg.js.example. Rename it to cfg.js and fill in the necessary requirements. This can all be found in the wiki.

**Comment by Rendaman13** [comment]
Your problem is almost certainly with cfg.js. Make sure you renamed cfg.js.example to cfg.js.

**Comment by Badley187** [comment]
14 error node v4.6.0
15 error npm v2.15.9

update your node.js

**Comment by WonThesSik** [comment]
Fixed that error, but new one came up

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'boot' ]
2 info using npm@3.10.8
3 info using node@v6.8.0
4 verbose run-script [ 'preboot', 'boot', 'postboot' ]
5 info lifecycle POGOServer@0.6.0~preboot: POGOServer@0.6.0
6 silly lifecycle POGOServer@0.6.0~preboot: no script for preboot, continuing
7 info lifecycle POGOServer@0.6.0~boot: POGOServer@0.6.0
8 verbose lifecycle POGOServer@0.6.0~boot: unsafe-perm in lifecycle true
9 verbose lifecycle POGOServer@0.6.0~boot: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\David\Desktop\PGM-3.2.0\server\node_modules\.bin;C:\Python27;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\CMake\bin;C:\Users\David\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\David\AppData\Local\Microsoft\WindowsApps;C:\Users\David\AppData\Roaming\npm
10 verbose lifecycle POGOServer@0.6.0~boot: CWD: C:\Users\David\Desktop\PGM-3.2.0\server
11 silly lifecycle POGOServer@0.6.0~boot: Args: [ '/d /s /c', 'npm run babel-node -- ./src/index.js' ]
12 silly lifecycle POGOServer@0.6.0~boot: Returned: code: 1  signal: null
13 info lifecycle POGOServer@0.6.0~boot: Failed to exec boot script
14 verbose stack Error: POGOServer@0.6.0 boot: `npm run babel-node -- ./src/index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid POGOServer@0.6.0
16 verbose cwd C:\Users\David\Desktop\PGM-3.2.0\server
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "boot"
19 error node v6.8.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error POGOServer@0.6.0 boot: `npm run babel-node -- ./src/index.js`
22 error Exit status 1
23 error Failed at the POGOServer@0.6.0 boot script 'npm run babel-node -- ./src/index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the POGOServer package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run babel-node -- ./src/index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs POGOServer
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls POGOServer
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Badley187** [comment]
dont use the bat files... type:    npm install node-protobuf && npm install
then :  npm run boot

**Comment by WonThesSik** [comment]
Same Error. I will try reinstalling the server and see if that fixes it

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\David\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'boot' ]
2 info using npm@3.10.8
3 info using node@v6.8.0
4 verbose run-script [ 'preboot', 'boot', 'postboot' ]
5 info lifecycle POGOServer@0.6.0~preboot: POGOServer@0.6.0
6 silly lifecycle POGOServer@0.6.0~preboot: no script for preboot, continuing
7 info lifecycle POGOServer@0.6.0~boot: POGOServer@0.6.0
8 verbose lifecycle POGOServer@0.6.0~boot: unsafe-perm in lifecycle true
9 verbose lifecycle POGOServer@0.6.0~boot: PATH: C:\Users\David\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\David\Desktop\PGM-3.2.0\server\node_modules\.bin;C:\Python27;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\CMake\bin;C:\Users\David\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\David\AppData\Local\Microsoft\WindowsApps;C:\Users\David\AppData\Roaming\npm
10 verbose lifecycle POGOServer@0.6.0~boot: CWD: C:\Users\David\Desktop\PGM-3.2.0\server
11 silly lifecycle POGOServer@0.6.0~boot: Args: [ '/d /s /c', 'npm run babel-node -- ./src/index.js' ]
12 silly lifecycle POGOServer@0.6.0~boot: Returned: code: 1  signal: null
13 info lifecycle POGOServer@0.6.0~boot: Failed to exec boot script
14 verbose stack Error: POGOServer@0.6.0 boot: `npm run babel-node -- ./src/index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\David\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\David\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid POGOServer@0.6.0
16 verbose cwd C:\Users\David\Desktop\PGM-3.2.0\server
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\David\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "boot"
19 error node v6.8.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error POGOServer@0.6.0 boot: `npm run babel-node -- ./src/index.js`
22 error Exit status 1
23 error Failed at the POGOServer@0.6.0 boot script 'npm run babel-node -- ./src/index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the POGOServer package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run babel-node -- ./src/index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs POGOServer
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls POGOServer
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by WonThesSik** [comment]
New protobuf error I didn't encounter last time

 Run Build Command:"nmake" "/NOLOGO" "cmTC_576ff\fast"
	"C:\Users\David\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\nmake.exe" -f CMakeFiles\cmTC_576ff.dir\build.make /nologo -L                  CMakeFiles\cmTC_576ff.dir\build

Building C object CMakeFiles/cmTC_576ff.dir/CheckIncludeFile.c.obj

	C:\Users\David\AppData\Local\Programs\Common\MICROS~1\VISUAL~1\9.0\VC\bin\amd64\cl.exe  @C:\Users\David\AppData\Local\Temp\nm1CCE.tmp

CheckIncludeFile.c

C:\Users\David\Desktop\PGM-3.2.0\server reinstall\protobuf\protobuf\cmake\build\release\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1) : fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory

NMAKE : fatal error U1077: 'C:\Users\David\AppData\Local\Programs\Common\MICROS~1\VISUAL~1\9.0\VC\bin\amd64\cl.exe' : return code '0x2'

Stop.

NMAKE : fatal error U1077: '"C:\Users\David\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\nmake.exe"' : return code '0x2'

Stop.

**Comment by WonThesSik** [comment]
Trying to recompile protobuf gives new error

Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/Users/David/Desktop/PGM-3.2.0/server reinstall/protobuf/protobuf/cmake/build/release/CMakeFiles/CMakeTmp

Run Build Command:"nmake" "/NOLOGO" "cmTC_68215\fast"
	"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe" -f CMakeFiles\cmTC_68215.dir\build.make /nologo -L                  CMakeFiles\cmTC_68215.dir\build

Building C object CMakeFiles/cmTC_68215.dir/CheckIncludeFile.c.obj

	C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe  @C:\Users\David\AppData\Local\Temp\nmC078.tmp

CheckIncludeFile.c

C:\Users\David\Desktop\PGM-3.2.0\server reinstall\protobuf\protobuf\cmake\build\release\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory

NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe' : return code '0x2'

Stop.

NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'

Stop.
