### ISSUE TITLE
Error after the Update

### ISSUE THREAD

**Issue by LUCKASSs** [maierfelix/POGOserver#288]
Hello guys,
I just updated the server (0.6.0 to 0.6.1) and it give me this error 

```
> POGOServer@0.6.1 boot /home/luca/POGOserver
> npm run babel-node -- ./src/index.js


> POGOServer@0.6.1 babel-node /home/luca/POGOserver
> babel-node --presets=es2015 "./src/index.js"

/home/luca/POGOserver/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/luca/POGOserver/node_modules/node-protobuf/build/protobuf.node
 → /home/luca/POGOserver/node_modules/node-protobuf/build/Debug/protobuf.node
 → /home/luca/POGOserver/node_modules/node-protobuf/build/Release/protobuf.node
 → /home/luca/POGOserver/node_modules/node-protobuf/out/Debug/protobuf.node
 → /home/luca/POGOserver/node_modules/node-protobuf/Debug/protobuf.node
 → /home/luca/POGOserver/node_modules/node-protobuf/out/Release/protobuf.node
 → /home/luca/POGOserver/node_modules/node-protobuf/Release/protobuf.node
 → /home/luca/POGOserver/node_modules/node-protobuf/build/default/protobuf.node
 → /home/luca/POGOserver/node_modules/node-protobuf/compiled/6.7.0/linux/arm/protobuf.node
    at bindings (/home/luca/POGOserver/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/luca/POGOserver/node_modules/node-protobuf/protobuf.js:9:35)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/luca/POGOserver/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
```

I have try to make a clean install and `npm cache clean && npm install` but it give me the same error on startup..

thx

**Comment by Badley187** [comment]
try npm install node-protobuf && npm install

**Comment by LUCKASSs** [comment]
Problem solved, I make another clean Install and this time I deleted protobuf and Reinstalled.
