### ISSUE TITLE
TypeError: Cannot read property 'digest' of undefined

### ISSUE THREAD

**Issue by yanrongmao** [maierfelix/POGOserver#29]
![image](https://cloud.githubusercontent.com/assets/17087982/17734628/05944fb0-64b0-11e6-85fa-620a8ec56390.png)
![image](https://cloud.githubusercontent.com/assets/17087982/17734647/1c2eb1d4-64b0-11e6-8838-f176c798e2c3.png)

**What's wrong with this? How can I solve it?**

**Comment by maierfelix** [comment]
Does the server print ``Created asset download session`` after booting?

**Comment by yanrongmao** [comment]
@maierfelix ![image](https://cloud.githubusercontent.com/assets/17087982/17734732/ad8ee5ea-64b0-11e6-9446-2d00f2bc3168.png)

**Comment by maierfelix** [comment]
Please post the full log. The message above db connection established is relevant

**Comment by yanrongmao** [comment]
@maierfelix 
E:\pokesever\POGOserver>npm run start

> POGOServer@0.2.7 start E:\pokesever\POGOserver
> nodemon --exec npm run babel-node -- ./src/index.js

[nodemon] 1.10.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `npm run babel-node ./src/index.js`

> POGOServer@0.2.7 babel-node E:\pokesever\POGOserver
> babel-node --presets=es2015 "./src/index.js"

            ______ _____ _____ _____
            | ___ \  _  |  __ \  _  |
            | |_/ / | | | |  \/ | | | ___  ___ _ ____   _____ _ __
            |  __/| | | | | __| | | |/ __|/ _ \ '__\ \ / / _ \ '__|
            | |   \ \_/ / |_\ \ \_/ /\__ \  __/ |   \ V /  __/ |
            \_|    \___/ \____/\___/ |___/\___|_|    \_/ \___|_|

[Console] Booting server..
[Console] Boot timeout, please check your login details!
[Console] Created asset download session
[Console] MySQL connection established
[Console] Server running at 127.0.0.1:3000
#####
Got request: GET_PLAYER
[Console] kejun1997 connected!
#####
Got request: GET_PLAYER
[Console] kejun1997 authenticated!
[Console] kejun1997 registered!
#####
Got request: DOWNLOAD_REMOTE_CONFIG_VERSION
Got request: GET_HATCHED_EGGS
Got request: GET_INVENTORY
Got request: CHECK_AWARDED_BADGES
Got request: DOWNLOAD_SETTINGS
#####
Got request: GET_ASSET_DIGEST
Got request: GET_HATCHED_EGGS
Got request: GET_INVENTORY
Got request: CHECK_AWARDED_BADGES
Got request: DOWNLOAD_SETTINGS
TypeError: Cannot read property 'digest' of undefined
    at GetAssetDigest (Responses.GetAssetDigest.js:16:3)
    at response.js:69:20
    at new Promise (E:\pokesever\POGOserver\node_modules\core-js\modules\es6.promise.js:191:7)
    at GameServer.processResponse (response.js:42:10)
    at loop (request.js:160:12)
    at request.js:167:5
    at new Promise (E:\pokesever\POGOserver\node_modules\core-js\modules\es6.promise.js:191:7)
    at GameServer.processRequests (request.js:153:10)
    at GameServer.onRequest (request.js:119:8)
    at GameServer.routeRequest (request.js:185:12)
    at IncomingMessage.<anonymous> (index.js:131:14)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

Here is, 
and then repeat the error

**Comment by maierfelix** [comment]
=> ``Boot timeout, please check your login details!``

Make sure to fill those fields: https://github.com/maierfelix/POGOserver/blob/master/cfg.js#L37

**Comment by yanrongmao** [comment]
E:\pokesever\POGOserver>npm run start

> POGOServer@0.2.7 start E:\pokesever\POGOserver
> nodemon --exec npm run babel-node -- ./src/index.js

[nodemon] 1.10.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `npm run babel-node ./src/index.js`

> POGOServer@0.2.7 babel-node E:\pokesever\POGOserver
> babel-node --presets=es2015 "./src/index.js"

            ______ _____ _____ _____
            | ___ \  _  |  __ \  _  |
            | |_/ / | | | |  \/ | | | ___  ___ _ ____   _____ _ __
            |  __/| | | | | __| | | |/ __|/ _ \ '__\ \ / / _ \ '__|
            | |   \ \_/ / |_\ \ \_/ /\__ \  __/ |   \ V /  __/ |
            \_|    \___/ \____/\___/ |___/\___|_|    \_/ \___|_|

[Console] Booting server..
[Console] Created asset download session
[Console] MySQL connection established
[Console] Server running at 127.0.0.1:3000
#####
Got request: GET_PLAYER
[Console] kejun1997 connected!
#####
Got request: GET_PLAYER
[Console] kejun1997 authenticated!
[Console] kejun1997 registered!
#####
Got request: DOWNLOAD_REMOTE_CONFIG_VERSION
Got request: GET_HATCHED_EGGS
Got request: GET_INVENTORY
Got request: CHECK_AWARDED_BADGES
Got request: DOWNLOAD_SETTINGS
#####
Got request: GET_ASSET_DIGEST
Got request: GET_HATCHED_EGGS
Got request: GET_INVENTORY
Got request: CHECK_AWARDED_BADGES
Got request: DOWNLOAD_SETTINGS
TypeError: Cannot read property 'digest' of undefined
    at GetAssetDigest (Responses.GetAssetDigest.js:16:3)
    at response.js:69:20
    at new Promise (E:\pokesever\POGOserver\node_modules\core-js\modules\es6.promise.js:191:7)
    at GameServer.processResponse (response.js:42:10)
    at loop (request.js:160:12)
    at request.js:167:5
    at new Promise (E:\pokesever\POGOserver\node_modules\core-js\modules\es6.promise.js:191:7)
    at GameServer.processRequests (request.js:153:10)
    at GameServer.onRequest (request.js:119:8)
    at GameServer.routeRequest (request.js:185:12)
    at IncomingMessage.<anonymous> (index.js:131:14)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

When it is normal, there is still an error.

**Comment by maierfelix** [comment]
Use a google account to login into the game.
If still not working, please join [this](https://discord.gg/gu8ZUJp) discord channel
