### ISSUE TITLE
I keep getting errors in the console

### ISSUE THREAD

**Issue by StoycsYT** [maierfelix/POGOserver#312]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'api' ]
2 info using npm@3.10.3
3 info using node@v6.4.0
4 verbose run-script [ 'preapi', 'api', 'postapi' ]
5 info lifecycle POGOServer@0.6.1~preapi: POGOServer@0.6.1
6 silly lifecycle POGOServer@0.6.1~preapi: no script for preapi, continuing
7 info lifecycle POGOServer@0.6.1~api: POGOServer@0.6.1
8 verbose lifecycle POGOServer@0.6.1~api: unsafe-perm in lifecycle true
9 verbose lifecycle POGOServer@0.6.1~api: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Mostafa\Desktop\POGOserver-master\node_modules\.bin;C:\Program Files\nodejs;C:\Users\Mostafa\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Users\Mostafa\AppData\Local\Microsoft\WindowsApps;C:\Users\Mostafa\AppData\Roaming\npm
10 verbose lifecycle POGOServer@0.6.1~api: CWD: C:\Users\Mostafa\Desktop\POGOserver-master
11 silly lifecycle POGOServer@0.6.1~api: Args: [ '/d /s /c', 'npm run babel-node -- ./api/index.js' ]
12 silly lifecycle POGOServer@0.6.1~api: Returned: code: 1  signal: null
13 info lifecycle POGOServer@0.6.1~api: Failed to exec api script
14 verbose stack Error: POGOServer@0.6.1 api: `npm run babel-node -- ./api/index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid POGOServer@0.6.1
16 verbose cwd C:\Users\Mostafa\Desktop\POGOserver-master
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "api"
19 error node v6.4.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error POGOServer@0.6.1 api: `npm run babel-node -- ./api/index.js`
22 error Exit status 1
23 error Failed at the POGOServer@0.6.1 api script 'npm run babel-node -- ./api/index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the POGOServer package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run babel-node -- ./api/index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs POGOServer
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls POGOServer
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

HELP

**Comment by StoycsYT** [comment]
and i have cmake,python and visual studios installed
