### ISSUE TITLE
Cannot set 'forts' of undefined

### ISSUE THREAD

**Issue by xomikronx** [maierfelix/POGOserver#40]
TypeError: Cannot set property 'forts' of undefined
    at GetMapObjects (Responses.GetMapObjects.js:39:3)
    at response.js:76:20
    at new Promise (/var/www/MYDOMAIN/POGOserver/node_modules/core-js/modules/es6.promise.js:191:7)
    at GameServer.processResponse (response.js:42:10)
    at loop (request.js:160:12)
    at request.js:167:5
    at new Promise (/var/www/MYDOMAIN/POGOserver/node_modules/core-js/modules/es6.promise.js:191:7)
    at GameServer.processRequests (request.js:153:10)
    at GameServer.onRequest (request.js:119:8)
    at GameServer.routeRequest (request.js:185:12)
    at IncomingMessage.<anonymous> (index.js:137:14)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by durankeeley** [comment]
Did you delete your node_modules folder when you updated your NodeJS version?
