### ISSUE TITLE
Error for install.

### ISSUE THREAD

**Issue by Kurimatzu** [maierfelix/POGOserver#65]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.10.3
3 info using node@v6.4.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchOtherPackageData pokemongo-protobuf@git+https://github.com/maierfelix/pokemon-go-protobuf-node.git
20 silly cache add args [ 'pokemongo-protobuf@git+https://github.com/maierfelix/pokemon-go-protobuf-node.git',
20 silly cache add   null ]
21 verbose cache add spec pokemongo-protobuf@git+https://github.com/maierfelix/pokemon-go-protobuf-node.git
22 silly cache add parsed spec Result {
22 silly cache add   raw: 'pokemongo-protobuf@git+https://github.com/maierfelix/pokemon-go-protobuf-node.git',
22 silly cache add   scope: null,
22 silly cache add   escapedName: 'pokemongo-protobuf',
22 silly cache add   name: 'pokemongo-protobuf',
22 silly cache add   rawSpec: 'git+https://github.com/maierfelix/pokemon-go-protobuf-node.git',
22 silly cache add   spec: 'git+https://github.com/maierfelix/pokemon-go-protobuf-node.git',
22 silly cache add   type: 'hosted',
22 silly cache add   hosted:
22 silly cache add    { type: 'github',
22 silly cache add      ssh: 'git@github.com:maierfelix/pokemon-go-protobuf-node.git',
22 silly cache add      sshUrl: 'git+ssh://git@github.com/maierfelix/pokemon-go-protobuf-node.git',
22 silly cache add      httpsUrl: 'git+https://github.com/maierfelix/pokemon-go-protobuf-node.git',
22 silly cache add      gitUrl: 'git://github.com/maierfelix/pokemon-go-protobuf-node.git',
22 silly cache add      shortcut: 'github:maierfelix/pokemon-go-protobuf-node',
22 silly cache add      directUrl: 'https://raw.githubusercontent.com/maierfelix/pokemon-go-protobuf-node/master/package.json' } }
23 verbose addRemoteGit caching git+https://github.com/maierfelix/pokemon-go-protobuf-node.git
24 verbose addRemoteGit git+https://github.com/maierfelix/pokemon-go-protobuf-node.git is a repository hosted by github
25 silly tryClone cloning git+https://github.com/maierfelix/pokemon-go-protobuf-node.git via git+https://github.com/maierfelix/pokemon-go-protobuf-node.git
26 verbose tryClone git-https-github-com-maierfelix-pokemon-go-protobuf-node-git-23032fc2 not in flight; caching
27 verbose correctMkdir C:\Users\User\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
28 info git [ 'config', '--get', 'remote.origin.url' ]
29 silly validateExistingRemote git+https://github.com/maierfelix/pokemon-go-protobuf-node.git remote.origin.url: https://github.com/maierfelix/pokemon-go-protobuf-node.git
30 verbose validateExistingRemote git+https://github.com/maierfelix/pokemon-go-protobuf-node.git is updating existing cached remote C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-maierfelix-pokemon-go-protobuf-node-git-23032fc2
31 info git [ 'fetch', '-a', 'origin' ]
32 error git fetch -a origin (https://github.com/maierfelix/pokemon-go-protobuf-node.git) fatal: unable to access 'https://github.com/maierfelix/pokemon-go-protobuf-node.git/': Couldn't resolve host 'github.com'
33 silly fetchPackageMetaData Error: Command failed: git -c core.longpaths=true fetch -a origin
33 silly fetchPackageMetaData fatal: unable to access 'https://github.com/maierfelix/pokemon-go-protobuf-node.git/': Couldn't resolve host 'github.com'
33 silly fetchPackageMetaData
33 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:206:12)
33 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
33 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
33 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:852:16)
33 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
33 silly fetchPackageMetaData  error for pokemongo-protobuf@git+https://github.com/maierfelix/pokemon-go-protobuf-node.git { Error: Command failed: git -c core.longpaths=true fetch -a origin
33 silly fetchPackageMetaData fatal: unable to access 'https://github.com/maierfelix/pokemon-go-protobuf-node.git/': Couldn't resolve host 'github.com'
33 silly fetchPackageMetaData
33 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:206:12)
33 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
33 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
33 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:852:16)
33 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
33 silly fetchPackageMetaData   killed: false,
33 silly fetchPackageMetaData   code: 128,
33 silly fetchPackageMetaData   signal: null,
33 silly fetchPackageMetaData   cmd: 'git -c core.longpaths=true fetch -a origin' }
34 silly rollbackFailedOptional Starting
35 silly rollbackFailedOptional Finishing
36 silly runTopLevelLifecycles Starting
37 silly runTopLevelLifecycles Finishing
38 silly install printInstalled
39 verbose stack Error: Command failed: git -c core.longpaths=true fetch -a origin
39 verbose stack fatal: unable to access 'https://github.com/maierfelix/pokemon-go-protobuf-node.git/': Couldn't resolve host 'github.com'
39 verbose stack
39 verbose stack     at ChildProcess.exithandler (child_process.js:206:12)
39 verbose stack     at emitTwo (events.js:106:13)
39 verbose stack     at ChildProcess.emit (events.js:191:7)
39 verbose stack     at maybeClose (internal/child_process.js:852:16)
39 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
40 verbose cwd C:\Users\User\Desktop\POGOserver-master
41 error Windows_NT 6.1.7601
42 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
43 error node v6.4.0
44 error npm  v3.10.3
45 error code 128
46 error Command failed: git -c core.longpaths=true fetch -a origin
46 error fatal: unable to access 'https://github.com/maierfelix/pokemon-go-protobuf-node.git/': Couldn't resolve host 'github.com'
47 error If you need help, you may report this error at:
47 error     <https://github.com/npm/npm/issues>
48 verbose exit [ 1, true ]

```

This error occurs when I click to install.

**Comment by Sygix** [comment]
I Think you can use this file : http://i.sygix.tk/POGOserver0.4.3.rar

**Comment by maierfelix** [comment]
Join the discord in the root readme

**Comment by shadowangelo** [comment]
how can i solve this? i have the same issue
