### ISSUE TITLE
Unhandled exception occurred:  undefined TypeError: this.spawnPkmnAtPlayer is not a function

### ISSUE THREAD

**Issue by srg84** [maierfelix/POGOserver#97]
Hi, Installed from 0 deleted  tables users and owned_pkmn.

At startup:

**[Console] SyntaxError: Unexpected token :**

/Spawn command

**Unhandled exception occurred:  undefined
TypeError: this.spawnPkmnAtPlayer is not a function**

(Master Branch)
The code is not fully updated?

**Comment by ruchern** [comment]
/Spawn or /spawn

I'm not too sure if this is case-sensitive.

**Comment by srg84** [comment]
[Console] SyntaxError: Unexpected token :
[Console] Booting Server v0.5.0
[Console] Downloaded assets are valid! Proceeding..
[Console] MySQL connection established
[Console] Server listening at 192.168.0.2:3000
/spawn paco MEW 2
Unhandled exception occurred:  undefined
TypeError: this.spawnPkmnAtPlayer is not a function
    at GameServer.processCommand (/mnt/188856D68856B24C/DATOS/Escritorio/POGOserver-master/src/process.js:44:12)
    at GameServer.stdinInput (/mnt/188856D68856B24C/DATOS/Escritorio/POGOserver-master/src/process.js:60:8)
    at ReadStream.<anonymous> (/mnt/188856D68856B24C/DATOS/Escritorio/POGOserver-master/src/index.js:193:12)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at ReadStream.Readable.push (_stream_readable.js:110:10)
    at TTY.onread (net.js:523:20)
[Console] The server has crashed!


Missing function in JS for any reason, that function dissapeared

**Comment by icdance** [comment]
spawn for .50 is not yet implemented

**Comment by RoccoDeveloping** [comment]
Hey! I cannot spawn pkmn either. Maybe it's because no players are online?

**Comment by RoccoDeveloping** [comment]
What are .50?
